### PR TITLE
Bug fix for issue #133 - using ConvergedServletContext in SipServletImpl

### PR DESCRIPTION
**Pull request by AlerantAppNGIN**
Hi Jean!

This PR consists a bug fix for issue#133. The SipServletImpl now stores the ConvergedServletContextImpl so getServletContext returns ConvergedServletContextImpl object which is able to handle getNamedDispatcher for sip servlets.
Although we did some tests but this modification needs to be double checked.

Best Regards,
Gabor & Istvan

### CODE REVIEW

**Comment by deruelle** [comment]
Can you make sure the license header for all files changes is the one from the [Open Source Playbook Licensing Section](https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.iayg4mgzyzs8)  ?

thanks

**Comment by AlerantAppNGIN** [comment]
Hi Jean!


This search shows that there are lot of files with different license headers:

> grep -LR "TeleStax, Open Source Cloud Communications" . | grep -e "\.java"


For example:

sip-servlets/containers/sip-servlets-as10/src/main/java/org/mobicents/servlet/sip/undertow/security/authentication/MD5Encoder.java

Do you want me to change their license header too or only for the new files which doesnt has a header at all?


Regards,

Gabor








________________________________
Feladó: Jean Deruelle <notifications@github.com>
Elküldve: 2016. április 28. 16:04:10
Címzett: RestComm/sip-servlets
Másolatot kap: AlerantAppNGIN; Author
Tárgy: Re: [RestComm/sip-servlets] Bug fix for issue #133 - using ConvergedServletContext in SipServletImpl (#136)


Can you make sure the license header for all files changes is the one from the Open Source Playbook Licensing Section<https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.iayg4mgzyzs8> ?

thanks

-

**Comment by deruelle** [comment]
@AlerantAppNGIN  Please change all for as10 and as8

**Comment by AlerantAppNGIN** [comment]
I've added the license headers.

Brgds
Gabor

**Pull request merged**
